#pragma once
#include<d3dx12.h>
const DXGI_FORMAT BackBufferFormat = DXGI_FORMAT_R8G8B8A8_UNORM;
const DXGI_FORMAT DepthStencilFormat = DXGI_FORMAT_D24_UNORM_S8_UINT;
const DXGI_FORMAT PositionFormat = DXGI_FORMAT_R8G8B8A8_UNORM;
const DXGI_FORMAT AlbedoFormat = DXGI_FORMAT_R8G8B8A8_UNORM;
const DXGI_FORMAT NormalFormat = DXGI_FORMAT_R8G8B8A8_UNORM;
const DXGI_FORMAT SpecularFormat = DXGI_FORMAT_R8G8B8A8_UNORM;
const DXGI_FORMAT RoughnessFormat = DXGI_FORMAT_R8G8B8A8_UNORM;
const DXGI_FORMAT MetalicFormat = DXGI_FORMAT_R8G8B8A8_UNORM;
const DXGI_FORMAT SSAOFormat = DXGI_FORMAT_R8G8B8A8_UNORM;